apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spawner
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spawner-role
  namespace: apps
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["create","get","list","watch","delete","patch","update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create","get","list","watch","delete","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spawner-binding
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: spawner
    namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spawner-role
