apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-fusion-mcp
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandbox-fusion-mcp
  template:
    metadata:
      labels:
        app: sandbox-fusion-mcp
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: mcp-servers
      containers:
      - name: sandbox-fusion-mcp
        image: timemagic/rl-mcp:sandbox-fusion-mcp
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: "1500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "1512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-fusion-mcp
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: sandbox-fusion-mcp
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800